name: plus_chat
description: Плюс Чат - современный мессенджер
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  audioplayers: ^5.2.1
  badges: ^3.1.2
  permission_handler: ^11.1.0
  open_file: ^3.3.2
  # --- ЗАВИСИМОСТЬ ---
  flutter_launcher_icons: ^0.13.1
  # --- /ЗАВИСИМОСТЬ ---

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  # --- DEV ЗАВИСИМОСТЬ (если используется в dev) ---
  # flutter_launcher_icons: ^0.13.1
  # --- /DEV ЗАВИСИМОСТЬ ---

flutter:
  uses-material-design: true
  assets:
    - assets/

# --- КОНФИГУРАЦИЯ ПЛАГИНА ---
flutter_launcher_icons:
  android: true
  ios: false # Установите в true, если нужно для iOS
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#075E54"
  adaptive_icon_foreground: "assets/icon.png"
# --- /КОНФИГУРАЦИЯ ПЛАГИНА ---
